version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-original}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        JAVA_VERSION: ${JAVA_VERSION:-17.0.11-amzn}
        GRADLE_VERSION: ${GRADLE_VERSION:-8.8}
        KOTLIN_VERSION: ${KOTLIN_VERSION:-2.0.0}
        LOCALE: ${LOCALE:-ja_JP.UTF-8}
    tty: true
    environment:
      TZ: ${TIME_ZONE:-Asia/Tokyo}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-dev}
      DB_USER: ${DB_USER:-dbuser}
      DB_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      DB_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      DB_DRIVER: ${DB_DRIVER:-org.postgresql.Driver}
      AUTHOR_API_DB_HOST: ${AUTHOR_API_DB_HOST:-author-api-postgres}
      AUTHOR_API_DB_NAME: ${AUTHOR_API_DB_NAME:-dev}
      AUTHOR_API_DB_USER: ${AUTHOR_API_DB_USER:-dbuser}
      AUTHOR_API_DB_URL: "jdbc:postgresql://${AUTHOR_API_DB_HOST}:${AUTHOR_API_DB_PORT}/${AUTHOR_API_DB_NAME}"
      AUTHOR_API_DB_PASSWORD: ${AUTHOR_API_DB_PASSWORD:-thisIsReallyStrongPassword123}
      AUTHOR_API_DB_DRIVER: ${AUTHOR_API_DB_DRIVER:-org.postgresql.Driver}
      NGINX_PORT: ${NGINX_PORT:-3333}
      GIT_USER: ${GIT_USER:-user}
      GIT_EMAIL: ${GIT_EMAIL:-email}
    volumes:
      - ../:/home/${USER_NAME:-vscode}/workspace:cached
      - ~/.aws:/home/${USER_NAME:-vscode}/.aws
    ports:
      - ${WORKSPACE_PORT:-9999}:9999

  author-api-postgres:
    container_name: ${PROJECT_NAME:-original}-author-api-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${AUTHOR_API_DB_USER:-dbuser}
      POSTGRES_PASSWORD: ${AUTHOR_API_DB_PASSWORD:-thisIsReallyStrongPassword123}
      POSTGRES_DB: ${AUTHOR_API_DB_NAME:-dev}
    ports:
      - 6543:5432
    volumes:
      - ../.docker/author_api_postgres:/var/lib/postgresql/data/
    restart: unless-stopped

  # postgres:
  #   container_name: ${PROJECT_NAME:-original}-postgres
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-dbuser}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
  #     POSTGRES_DB: ${DB_NAME:-dev}
  #   ports:
  #     - ${DB_PORT:-5432}:5432
  #   volumes:
  #     - ../.docker/postgres:/var/lib/postgresql/data/
  #   restart: unless-stopped

  nginx:
    build:
      context: ./docker/nginx
    container_name: ${PROJECT_NAME:-original}-nginx
    ports:
      - ${NGINX_PORT:-3333}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
